project:
  type: website

website:
  title: "Malo - Stokes' Theorem"
  sidebar:
    style: "docked"
    search: true
    contents:
      - href: index.qmd
        text: Home
      - text: "Core Topics"
        contents:
          - href: Stokes_Theorem.qmd
            text: Stokes' Theorem
        
          
format:
  html:
    theme: cosmo
    toc: true